// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgv3u6Dao4P-HbuPCPQlD81haPd_X6hBA',
    appId: '1:152816784658:web:752fe8773933c42c494fcb',
    messagingSenderId: '152816784658',
    projectId: 'placement-prep-app-2fb96',
    authDomain: 'placement-prep-app-2fb96.firebaseapp.com',
    storageBucket: 'placement-prep-app-2fb96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFsrn9deWZMEuZP_-n9iUPJS61dcIu2KI',
    appId: '1:152816784658:android:59c97095bc82a6d2494fcb',
    messagingSenderId: '152816784658',
    projectId: 'placement-prep-app-2fb96',
    storageBucket: 'placement-prep-app-2fb96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFt8ayfumxRHLRTo-gx7MifS72SGA-llA',
    appId: '1:152816784658:ios:43eeb70f13ae2208494fcb',
    messagingSenderId: '152816784658',
    projectId: 'placement-prep-app-2fb96',
    storageBucket: 'placement-prep-app-2fb96.firebasestorage.app',
    iosBundleId: 'com.example.placementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFt8ayfumxRHLRTo-gx7MifS72SGA-llA',
    appId: '1:152816784658:ios:43eeb70f13ae2208494fcb',
    messagingSenderId: '152816784658',
    projectId: 'placement-prep-app-2fb96',
    storageBucket: 'placement-prep-app-2fb96.firebasestorage.app',
    iosBundleId: 'com.example.placementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgv3u6Dao4P-HbuPCPQlD81haPd_X6hBA',
    appId: '1:152816784658:web:57db2f747cd1daba494fcb',
    messagingSenderId: '152816784658',
    projectId: 'placement-prep-app-2fb96',
    authDomain: 'placement-prep-app-2fb96.firebaseapp.com',
    storageBucket: 'placement-prep-app-2fb96.firebasestorage.app',
  );
}
